### ISSUE TITLE
Add Contributing.md file

### ISSUE THREAD

**Issue by amitkumar-y** [AllenShintani/Edison#37]
I suggest adding a contributing.md file to the project. You can assign this task to me, and I will create the file

**Comment by AllenShintani** [comment]
Thank you for your suggestion!
Before assigning the task to you, we'd like to understand a bit more about your plan. Could you please provide a brief outline or a few key points about what you intend to include in the contributing.md file?

**Comment by amitkumar-y** [comment]
We can cover the following points in the contributing.md file
1. What do I need to know to help?
2. What can you contribute? 
3. How do I make a contribution?

Basically, we will provide details about when and what people can contribute and we will explain the basic flow of forking and a pull request.
Let me know your thoughts, if you want to mention anything specifically then we can do that as well.

**Comment by AllenShintani** [comment]
I understand. I will assign this ISSUE to you.

1. Please specify the difference between how to run the system in WSL and Windows.
2. anyone can send PR or ISSUE.
3. please label the ISSUE with the corresponding label. If an appropriate label does not exist, it is not required.
Don't hesitate to create an ISSUE or send a PR.
5. we will work together with users and contributors to develop the necessary features, devices, etc. The development of this OSS will be carried out in a scrum style.
6. we respect all contributors and users.

If you have any questions, please feel free to ask.
Please keep the above in mind when creating files.
Thank you in advance!

**Comment by amitkumar-y** [comment]
Hi @AllenShintani ,
As discussed I have added the `contributing.md` file in this [PR](https://github.com/AllenShintani/Edison/pull/46).
I have included almost all the points that you suggested [here](https://github.com/AllenShintani/Edison/issues/37#issuecomment-1763455725). However, I think details about `how to run the system in WSL and Windows` are partially available in the Readme file so I have not included that here.

I think it would be good if those details were added in the Readme file entirely then it will be helpful for contributors.
If you still want to add those details in this file, then please share the exact details, and I will add them as well. Please let me know if you have any other suggestions, I will make the required changes.
