### ISSUE TITLE
Add a repository information about

### ISSUE THREAD

**Issue by chanon-mike** [AllenShintani/Edison#38]
## Suggestions 
I propose adding a brief description of the repository's functionality and a direct link to the documentation (https://edison-js-document.vercel.app/) on the "About" page. This will provide a clearer understanding of the repository's purpose and offer easy access to the documentation.

Here is the suggestion for bio
- TypeScript for Arduino
- Arduino programming with TypeScript

Feel free to adjust the bio as needed; these are just suggestions to provide more context about what the repository offers.

**Comment by AllenShintani** [comment]
Thank you. I will do the details later.
Right now I'm just trying to get more devices and development systems in place as soon as possible.

**Comment by AllenShintani** [comment]
I'd added info of repo! 
I'll close this issue
