### ISSUE TITLE
NANO EVERY対応

### ISSUE THREAD

**Issue by solufa** [AllenShintani/Edison#53]
- 正規品でもmanufacturerがArduinoではない（friendlyNameにArduinoが含まれる）
- 上記の対応でconnectManualを使っているせいなのか、あるいはセンサーの反応が過剰なのか、ホールセンサーが1回に2度反応してしまう

**Comment by AllenShintani** [comment]
I'll reply in English so others can see. Thanks for reporting the bug!
The cause was chunking when using connectManual and the data was not being read correctly.
We have fixed it in version 0.1.32, so please upgrade your version!
